_wandb:
    value:
        cli_version: 0.18.5
        code_path: code/src/models/train_baseline_models.py
        m: []
        python_version: 3.11.4
        session_history: code/_session_history.ipynb
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.5
            "8":
                - 1
                - 2
                - 5
            "10":
                - 3
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
class_imbalance_handling:
    value: WeightedRandomSampler
epochs:
    value: 50
image_size:
    value: 224x224
learning_rate:
    value: 0.001
